fix: autopif update
since google no longer exposing beta rom after October and old autopif still seems to work, let's just use it.

diff --git a/.github/workflows/autopif.yml b/.github/workflows/autopif.yml
--- a/.github/workflows/autopif.yml
+++ b/.github/workflows/autopif.yml
@@ -20,7 +20,7 @@ jobs:
       ota_hash: ${{ steps.get_info.outputs.ota_hash }}
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v5
+      uses: actions/checkout@v6
       with:
         fetch-depth: 1
         ref: bot
@@ -34,13 +34,16 @@ jobs:
         download https://developer.android.com/about/versions PIXEL_VERSIONS_HTML
         download "$(grep -o 'https://developer.android.com/about/versions/.*[0-9]"' PIXEL_VERSIONS_HTML | sort -ru | cut -d\" -f1 | head -n1)" PIXEL_LATEST_HTML
         download "https://developer.android.com$(grep -o 'href=".*download-ota.*"' PIXEL_LATEST_HTML | grep 'qpr' | cut -d\" -f2 | head -n1)" PIXEL_OTA_HTML
+        download https://developer.android.com/topic/generic-system-image/releases PIXEL_GSI_HTML
 
         # Extract device information
         grep -A1 'tr id=' PIXEL_OTA_HTML | grep 'td' | sed 's;.*<td>\(.*\)</td>;\1;' > MODEL_LIST
         grep -o 'tr id="[^\"]*"' PIXEL_OTA_HTML | awk -F\" '{print $2 "_beta"}' > PRODUCT_LIST
         grep 'ota/.*_beta' PIXEL_OTA_HTML | cut -d\" -f2 > OTA_LIST
+        grep -m1 'corresponding Google Pixel builds' PIXEL_GSI_HTML | grep -o '/versions/.*' | cut -d/ -f3 > RELEASE
 
-        CURRENT_HASH=$(sha256sum OTA_LIST | cut -d' ' -f1)
+        # CURRENT_HASH=$(sha256sum OTA_LIST | cut -d' ' -f1)
+        CURRENT_HASH=$(sha256sum RELEASE | cut -d' ' -f1)
         LAST_HASH=$(cat ../HASH || echo '')
 
         if [ "$CURRENT_HASH" == "$LAST_HASH" ] && [ "${{ github.event.inputs.force_update }}" != "true" ]; then
@@ -63,7 +66,7 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v5
+      uses: actions/checkout@v6
       with:
         fetch-depth: 1
         ref: bot
@@ -82,8 +85,9 @@ jobs:
       run: |
         model="${{ matrix.model }}"
         product="${{ matrix.product }}"
-        ota_link="${{ matrix.ota_link }}"
+        # ota_link="${{ matrix.ota_link }}"
 
+        ##############################################################################################################################
         # Download avbtool
         # curl -Ls https://android.googlesource.com/platform/external/avb/+/master/avbtool.py?format=TEXT | base64 -d > avbtool.py
 
@@ -97,9 +101,34 @@ jobs:
         # DIGEST=$(avbtool calculate_vbmeta_digest --image vbmeta.img)
 
         # Get other information
-        payload_dumper --metadata --out . "$ota_link"
-        FINGERPRINT=$(grep -am1 'post-build=' metadata | cut -d= -f2)
-        SECURITY_PATCH=$(grep -am1 'security-patch-level=' metadata | cut -d= -f2)
+        # payload_dumper --metadata --out . "$ota_link"
+        # FINGERPRINT=$(grep -am1 'post-build=' metadata | cut -d= -f2)
+        # SECURITY_PATCH=$(grep -am1 'security-patch-level=' metadata | cut -d= -f2)
+        ##############################################################################################################################
+
+        download() { wget -T 20 --no-check-certificate "$1" -O "$2"; }
+
+        # Get fingerprint detail
+        download https://developer.android.com/topic/generic-system-image/releases PIXEL_GSI_HTML
+        RELEASE="$(grep -m1 'corresponding Google Pixel builds' PIXEL_GSI_HTML | grep -o '/versions/.*' | cut -d/ -f3)"
+        ID="$(grep -m1 -o 'Build:.*' PIXEL_GSI_HTML | cut -d' ' -f2)"
+        INCREMENTAL="$(grep -m1 -o "$ID-.*-" PIXEL_GSI_HTML | cut -d- -f2)"
+
+        # Get security patch
+        download https://source.android.com/docs/security/bulletin/pixel PIXEL_SECBULL_HTML
+        SECURITY_PATCH="$(grep -A15 "$(grep -m1 -o 'Security patch level:.*' PIXEL_GSI_HTML | cut -d' ' -f4-)" PIXEL_SECBULL_HTML | grep -m1 -B1 '</tr>' | grep 'td' | sed 's;.*<td>\(.*\)</td>;\1;')"
+
+        DEVICE=$(echo "$product" | sed 's/_beta//')
+        FINGERPRINT="google/$product/$DEVICE:$RELEASE/$ID/$INCREMENTAL:user/release-keys"
+
+        # Validate required fields
+        required="model product DEVICE RELEASE ID INCREMENTAL SECURITY_PATCH"
+        for i in $required; do
+          if [ -z "${!i}" ]; then
+            echo "Missing $i"
+            exit 1
+          fi
+        done
 
         cat <<EOF > ../${product}.prop
         FINGERPRINT=$FINGERPRINT
@@ -120,7 +149,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v5
+      uses: actions/checkout@v6
       with:
         fetch-depth: 1
         ref: bot
